/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ProductVariant = IDL.Record({
  'id' : IDL.Text,
  'color' : IDL.Opt(IDL.Text),
  'size' : IDL.Opt(IDL.Text),
  'stock' : IDL.Nat,
  'price' : IDL.Opt(IDL.Float64),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Product = IDL.Record({
  'id' : IDL.Text,
  'mrp' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'variants' : IDL.Vec(ProductVariant),
  'seller' : IDL.Principal,
  'isActive' : IDL.Bool,
  'stock' : IDL.Nat,
  'category' : IDL.Text,
  'image' : ExternalBlob,
  'price' : IDL.Nat,
});
export const AddressLabel = IDL.Variant({
  'other' : IDL.Null,
  'home' : IDL.Null,
  'office' : IDL.Null,
});
export const SavedAddress = IDL.Record({
  'id' : IDL.Text,
  'tag' : AddressLabel,
  'street' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'state' : IDL.Text,
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
});
export const CartItem = IDL.Record({
  'productId' : IDL.Text,
  'seller' : IDL.Principal,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const CouponPublic = IDL.Record({
  'validFrom' : IDL.Int,
  'code' : IDL.Text,
  'usedCount' : IDL.Nat,
  'discountPercent' : IDL.Nat,
  'validTo' : IDL.Int,
  'isActive' : IDL.Bool,
  'usageLimit' : IDL.Nat,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'approved' : IDL.Null,
  'return_requested' : IDL.Null,
  'return_approved' : IDL.Null,
  'delivered' : IDL.Null,
  'return_rejected' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'status' : OrderStatus,
  'deliveryAddress' : IDL.Opt(IDL.Text),
  'paymentMethod' : IDL.Variant({ 'cod' : IDL.Null, 'online' : IDL.Null }),
  'totalAmount' : IDL.Nat,
  'timestamp' : IDL.Int,
  'buyer' : IDL.Principal,
  'items' : IDL.Vec(CartItem),
});
export const ReturnStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const ReturnRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : ReturnStatus,
  'orderId' : IDL.Text,
  'adminComment' : IDL.Opt(IDL.Text),
  'buyerId' : IDL.Principal,
  'timestamp' : IDL.Int,
  'reason' : IDL.Text,
});
export const SellerInfo = IDL.Record({
  'status' : IDL.Text,
  'principal' : IDL.Principal,
  'shopDescription' : IDL.Opt(IDL.Text),
  'shopName' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'shopDescription' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'role' : IDL.Text,
  'sellerApproved' : IDL.Bool,
  'shopName' : IDL.Opt(IDL.Text),
});
export const SellerRegistration = IDL.Record({
  'principal' : IDL.Principal,
  'shopDescription' : IDL.Opt(IDL.Text),
  'shopName' : IDL.Text,
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'reviewText' : IDL.Text,
  'productId' : IDL.Text,
  'buyerId' : IDL.Principal,
  'timestamp' : IDL.Int,
  'rating' : IDL.Nat,
  'buyerName' : IDL.Text,
});
export const ReferralStats = IDL.Record({
  'bonusPointsEarned' : IDL.Nat,
  'referralCode' : IDL.Text,
  'successfulReferrals' : IDL.Nat,
  'totalReferrals' : IDL.Nat,
});
export const ReviewSummary = IDL.Record({
  'productId' : IDL.Text,
  'averageRating' : IDL.Float64,
  'reviewCount' : IDL.Nat,
});
export const SellerProfileData = IDL.Record({
  'principal' : IDL.Principal,
  'shopDescription' : IDL.Opt(IDL.Text),
  'productCount' : IDL.Nat,
  'averageRating' : IDL.Float64,
  'shopName' : IDL.Text,
  'totalReviews' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const RedeemResult = IDL.Variant({
  'ok' : IDL.Record({ 'discountAmount' : IDL.Nat, 'pointsUsed' : IDL.Nat }),
  'err' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addProduct' : IDL.Func([Product], [], []),
  'addProductVariant' : IDL.Func(
      [IDL.Text, ProductVariant],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'addReview' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'addSavedAddress' : IDL.Func(
      [SavedAddress],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'addToCart' : IDL.Func([CartItem], [], []),
  'addToWishlist' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'applyCoupon' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'applyReferralCode' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'approveReturn' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'approveSeller' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimAdminRole' : IDL.Func([], [], []),
  'clearCallerCart' : IDL.Func([], [], []),
  'clearCart' : IDL.Func([], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createCoupon' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Int, IDL.Int, IDL.Nat],
      [IDL.Variant({ 'ok' : CouponPublic, 'err' : IDL.Text })],
      [],
    ),
  'deactivateCoupon' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'deleteSavedAddress' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getAllActiveCoupons' : IDL.Func([], [IDL.Vec(CouponPublic)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllReturnRequests' : IDL.Func([], [IDL.Vec(ReturnRequest)], ['query']),
  'getAllSellers' : IDL.Func([], [IDL.Vec(SellerInfo)], ['query']),
  'getCallerCart' : IDL.Func([], [IDL.Opt(IDL.Vec(CartItem))], ['query']),
  'getCallerSellerStatus' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerWishlist' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getLoyaltyPoints' : IDL.Func([], [IDL.Nat], ['query']),
  'getMyReturnRequests' : IDL.Func([], [IDL.Vec(ReturnRequest)], ['query']),
  'getOrderCommissionBreakdown' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'adminCommission' : IDL.Nat,
            'sellerPayments' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat)),
          })
        ),
      ],
      ['query'],
    ),
  'getPendingSellerDetails' : IDL.Func(
      [],
      [IDL.Vec(SellerRegistration)],
      ['query'],
    ),
  'getPendingSellerRegistrations' : IDL.Func(
      [],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getPlatformEarnings' : IDL.Func([], [IDL.Nat], ['query']),
  'getProductAverageRating' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
  'getProductReviews' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
  'getProductVariants' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProductVariant)],
      ['query'],
    ),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getReferralCode' : IDL.Func([], [IDL.Text], []),
  'getReferralStats' : IDL.Func([], [ReferralStats], ['query']),
  'getReturnRequestByOrder' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ReturnRequest)],
      ['query'],
    ),
  'getReviewSummaries' : IDL.Func([], [IDL.Vec(ReviewSummary)], ['query']),
  'getSavedAddresses' : IDL.Func([], [IDL.Vec(SavedAddress)], ['query']),
  'getSellerOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getSellerProducts' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getSellerProfileData' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(SellerProfileData)],
      ['query'],
    ),
  'getSellerReviews' : IDL.Func(
      [IDL.Principal, IDL.Nat],
      [IDL.Vec(Review)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getUserProducts' : IDL.Func([IDL.Principal], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerSellerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isInWishlist' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listCoupons' : IDL.Func([], [IDL.Vec(CouponPublic)], ['query']),
  'placeOrder' : IDL.Func([Order], [], []),
  'redeemLoyaltyPoints' : IDL.Func([IDL.Nat, IDL.Nat], [RedeemResult], []),
  'registerAsSeller' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'registerUser' : IDL.Func([], [], []),
  'rejectReturn' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'rejectSeller' : IDL.Func([IDL.Principal], [], []),
  'removeFromWishlist' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'requestApproval' : IDL.Func([], [], []),
  'safeIsCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitReturnRequest' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : ReturnRequest, 'err' : IDL.Text })],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
  'updateProductVariants' : IDL.Func(
      [IDL.Text, IDL.Vec(ProductVariant)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateSavedAddress' : IDL.Func(
      [SavedAddress],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateSellerOrderStatus' : IDL.Func(
      [
        IDL.Text,
        IDL.Variant({
          'shipped' : IDL.Null,
          'cancelled' : IDL.Null,
          'pending' : IDL.Null,
          'paid' : IDL.Null,
          'approved' : IDL.Null,
          'return_requested' : IDL.Null,
          'return_approved' : IDL.Null,
          'delivered' : IDL.Null,
          'return_rejected' : IDL.Null,
        }),
      ],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'validateCoupon' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ProductVariant = IDL.Record({
    'id' : IDL.Text,
    'color' : IDL.Opt(IDL.Text),
    'size' : IDL.Opt(IDL.Text),
    'stock' : IDL.Nat,
    'price' : IDL.Opt(IDL.Float64),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Product = IDL.Record({
    'id' : IDL.Text,
    'mrp' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'variants' : IDL.Vec(ProductVariant),
    'seller' : IDL.Principal,
    'isActive' : IDL.Bool,
    'stock' : IDL.Nat,
    'category' : IDL.Text,
    'image' : ExternalBlob,
    'price' : IDL.Nat,
  });
  const AddressLabel = IDL.Variant({
    'other' : IDL.Null,
    'home' : IDL.Null,
    'office' : IDL.Null,
  });
  const SavedAddress = IDL.Record({
    'id' : IDL.Text,
    'tag' : AddressLabel,
    'street' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'state' : IDL.Text,
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const CartItem = IDL.Record({
    'productId' : IDL.Text,
    'seller' : IDL.Principal,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const CouponPublic = IDL.Record({
    'validFrom' : IDL.Int,
    'code' : IDL.Text,
    'usedCount' : IDL.Nat,
    'discountPercent' : IDL.Nat,
    'validTo' : IDL.Int,
    'isActive' : IDL.Bool,
    'usageLimit' : IDL.Nat,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'approved' : IDL.Null,
    'return_requested' : IDL.Null,
    'return_approved' : IDL.Null,
    'delivered' : IDL.Null,
    'return_rejected' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'status' : OrderStatus,
    'deliveryAddress' : IDL.Opt(IDL.Text),
    'paymentMethod' : IDL.Variant({ 'cod' : IDL.Null, 'online' : IDL.Null }),
    'totalAmount' : IDL.Nat,
    'timestamp' : IDL.Int,
    'buyer' : IDL.Principal,
    'items' : IDL.Vec(CartItem),
  });
  const ReturnStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const ReturnRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : ReturnStatus,
    'orderId' : IDL.Text,
    'adminComment' : IDL.Opt(IDL.Text),
    'buyerId' : IDL.Principal,
    'timestamp' : IDL.Int,
    'reason' : IDL.Text,
  });
  const SellerInfo = IDL.Record({
    'status' : IDL.Text,
    'principal' : IDL.Principal,
    'shopDescription' : IDL.Opt(IDL.Text),
    'shopName' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'shopDescription' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'role' : IDL.Text,
    'sellerApproved' : IDL.Bool,
    'shopName' : IDL.Opt(IDL.Text),
  });
  const SellerRegistration = IDL.Record({
    'principal' : IDL.Principal,
    'shopDescription' : IDL.Opt(IDL.Text),
    'shopName' : IDL.Text,
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'reviewText' : IDL.Text,
    'productId' : IDL.Text,
    'buyerId' : IDL.Principal,
    'timestamp' : IDL.Int,
    'rating' : IDL.Nat,
    'buyerName' : IDL.Text,
  });
  const ReferralStats = IDL.Record({
    'bonusPointsEarned' : IDL.Nat,
    'referralCode' : IDL.Text,
    'successfulReferrals' : IDL.Nat,
    'totalReferrals' : IDL.Nat,
  });
  const ReviewSummary = IDL.Record({
    'productId' : IDL.Text,
    'averageRating' : IDL.Float64,
    'reviewCount' : IDL.Nat,
  });
  const SellerProfileData = IDL.Record({
    'principal' : IDL.Principal,
    'shopDescription' : IDL.Opt(IDL.Text),
    'productCount' : IDL.Nat,
    'averageRating' : IDL.Float64,
    'shopName' : IDL.Text,
    'totalReviews' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const RedeemResult = IDL.Variant({
    'ok' : IDL.Record({ 'discountAmount' : IDL.Nat, 'pointsUsed' : IDL.Nat }),
    'err' : IDL.Text,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addProduct' : IDL.Func([Product], [], []),
    'addProductVariant' : IDL.Func(
        [IDL.Text, ProductVariant],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'addReview' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'addSavedAddress' : IDL.Func(
        [SavedAddress],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'addToCart' : IDL.Func([CartItem], [], []),
    'addToWishlist' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'applyCoupon' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'applyReferralCode' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'approveReturn' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'approveSeller' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimAdminRole' : IDL.Func([], [], []),
    'clearCallerCart' : IDL.Func([], [], []),
    'clearCart' : IDL.Func([], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createCoupon' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Int, IDL.Int, IDL.Nat],
        [IDL.Variant({ 'ok' : CouponPublic, 'err' : IDL.Text })],
        [],
      ),
    'deactivateCoupon' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'deleteSavedAddress' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getAllActiveCoupons' : IDL.Func([], [IDL.Vec(CouponPublic)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllReturnRequests' : IDL.Func([], [IDL.Vec(ReturnRequest)], ['query']),
    'getAllSellers' : IDL.Func([], [IDL.Vec(SellerInfo)], ['query']),
    'getCallerCart' : IDL.Func([], [IDL.Opt(IDL.Vec(CartItem))], ['query']),
    'getCallerSellerStatus' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerWishlist' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getLoyaltyPoints' : IDL.Func([], [IDL.Nat], ['query']),
    'getMyReturnRequests' : IDL.Func([], [IDL.Vec(ReturnRequest)], ['query']),
    'getOrderCommissionBreakdown' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'adminCommission' : IDL.Nat,
              'sellerPayments' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat)),
            })
          ),
        ],
        ['query'],
      ),
    'getPendingSellerDetails' : IDL.Func(
        [],
        [IDL.Vec(SellerRegistration)],
        ['query'],
      ),
    'getPendingSellerRegistrations' : IDL.Func(
        [],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getPlatformEarnings' : IDL.Func([], [IDL.Nat], ['query']),
    'getProductAverageRating' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
    'getProductReviews' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
    'getProductVariants' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProductVariant)],
        ['query'],
      ),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getReferralCode' : IDL.Func([], [IDL.Text], []),
    'getReferralStats' : IDL.Func([], [ReferralStats], ['query']),
    'getReturnRequestByOrder' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ReturnRequest)],
        ['query'],
      ),
    'getReviewSummaries' : IDL.Func([], [IDL.Vec(ReviewSummary)], ['query']),
    'getSavedAddresses' : IDL.Func([], [IDL.Vec(SavedAddress)], ['query']),
    'getSellerOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
    'getSellerProducts' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getSellerProfileData' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(SellerProfileData)],
        ['query'],
      ),
    'getSellerReviews' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [IDL.Vec(Review)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
    'getUserProducts' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerSellerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isInWishlist' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listCoupons' : IDL.Func([], [IDL.Vec(CouponPublic)], ['query']),
    'placeOrder' : IDL.Func([Order], [], []),
    'redeemLoyaltyPoints' : IDL.Func([IDL.Nat, IDL.Nat], [RedeemResult], []),
    'registerAsSeller' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'registerUser' : IDL.Func([], [], []),
    'rejectReturn' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'rejectSeller' : IDL.Func([IDL.Principal], [], []),
    'removeFromWishlist' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'requestApproval' : IDL.Func([], [], []),
    'safeIsCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitReturnRequest' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : ReturnRequest, 'err' : IDL.Text })],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
    'updateProductVariants' : IDL.Func(
        [IDL.Text, IDL.Vec(ProductVariant)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateSavedAddress' : IDL.Func(
        [SavedAddress],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateSellerOrderStatus' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({
            'shipped' : IDL.Null,
            'cancelled' : IDL.Null,
            'pending' : IDL.Null,
            'paid' : IDL.Null,
            'approved' : IDL.Null,
            'return_requested' : IDL.Null,
            'return_approved' : IDL.Null,
            'delivered' : IDL.Null,
            'return_rejected' : IDL.Null,
          }),
        ],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'validateCoupon' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };