/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AddressLabel = { 'other' : null } |
  { 'home' : null } |
  { 'office' : null };
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface CartItem {
  'productId' : string,
  'seller' : Principal,
  'quantity' : bigint,
  'price' : bigint,
}
export interface CouponPublic {
  'validFrom' : bigint,
  'code' : string,
  'usedCount' : bigint,
  'discountPercent' : bigint,
  'validTo' : bigint,
  'isActive' : boolean,
  'usageLimit' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : string,
  'status' : OrderStatus,
  'deliveryAddress' : [] | [string],
  'paymentMethod' : { 'cod' : null } |
    { 'online' : null },
  'totalAmount' : bigint,
  'timestamp' : bigint,
  'buyer' : Principal,
  'items' : Array<CartItem>,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'paid' : null } |
  { 'approved' : null } |
  { 'return_requested' : null } |
  { 'return_approved' : null } |
  { 'delivered' : null } |
  { 'return_rejected' : null };
export interface Product {
  'id' : string,
  'mrp' : bigint,
  'title' : string,
  'description' : string,
  'discountPercent' : bigint,
  'variants' : Array<ProductVariant>,
  'seller' : Principal,
  'isActive' : boolean,
  'stock' : bigint,
  'category' : string,
  'image' : ExternalBlob,
  'price' : bigint,
}
export interface ProductVariant {
  'id' : string,
  'color' : [] | [string],
  'size' : [] | [string],
  'stock' : bigint,
  'price' : [] | [number],
}
export type RedeemResult = {
    'ok' : { 'discountAmount' : bigint, 'pointsUsed' : bigint }
  } |
  { 'err' : string };
export interface ReferralStats {
  'bonusPointsEarned' : bigint,
  'referralCode' : string,
  'successfulReferrals' : bigint,
  'totalReferrals' : bigint,
}
export interface ReturnRequest {
  'id' : string,
  'status' : ReturnStatus,
  'orderId' : string,
  'adminComment' : [] | [string],
  'buyerId' : Principal,
  'timestamp' : bigint,
  'reason' : string,
}
export type ReturnStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Review {
  'id' : bigint,
  'reviewText' : string,
  'productId' : string,
  'buyerId' : Principal,
  'timestamp' : bigint,
  'rating' : bigint,
  'buyerName' : string,
}
export interface ReviewSummary {
  'productId' : string,
  'averageRating' : number,
  'reviewCount' : bigint,
}
export interface SavedAddress {
  'id' : string,
  'tag' : AddressLabel,
  'street' : string,
  'city' : string,
  'name' : string,
  'state' : string,
  'phone' : string,
  'pincode' : string,
}
export interface SellerInfo {
  'status' : string,
  'principal' : Principal,
  'shopDescription' : [] | [string],
  'shopName' : string,
}
export interface SellerProfileData {
  'principal' : Principal,
  'shopDescription' : [] | [string],
  'productCount' : bigint,
  'averageRating' : number,
  'shopName' : string,
  'totalReviews' : bigint,
}
export interface SellerRegistration {
  'principal' : Principal,
  'shopDescription' : [] | [string],
  'shopName' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'shopDescription' : [] | [string],
  'name' : string,
  'role' : string,
  'sellerApproved' : boolean,
  'shopName' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'addProductVariant' : ActorMethod<
    [string, ProductVariant],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'addReview' : ActorMethod<
    [string, bigint, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'addSavedAddress' : ActorMethod<
    [SavedAddress],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'addToCart' : ActorMethod<[CartItem], undefined>,
  'addToWishlist' : ActorMethod<[string], boolean>,
  'applyCoupon' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'applyReferralCode' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'approveReturn' : ActorMethod<
    [string, [] | [string]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'approveSeller' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimAdminRole' : ActorMethod<[], undefined>,
  'clearCallerCart' : ActorMethod<[], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createCoupon' : ActorMethod<
    [string, bigint, bigint, bigint, bigint],
    { 'ok' : CouponPublic } |
      { 'err' : string }
  >,
  'deactivateCoupon' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'deleteSavedAddress' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'getAllActiveCoupons' : ActorMethod<[], Array<CouponPublic>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllReturnRequests' : ActorMethod<[], Array<ReturnRequest>>,
  'getAllSellers' : ActorMethod<[], Array<SellerInfo>>,
  'getCallerCart' : ActorMethod<[], [] | [Array<CartItem>]>,
  'getCallerSellerStatus' : ActorMethod<[], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCallerWishlist' : ActorMethod<[], Array<string>>,
  'getLoyaltyPoints' : ActorMethod<[], bigint>,
  'getMyReturnRequests' : ActorMethod<[], Array<ReturnRequest>>,
  'getOrderCommissionBreakdown' : ActorMethod<
    [string],
    [] | [
      {
        'adminCommission' : bigint,
        'sellerPayments' : Array<[Principal, bigint]>,
      }
    ]
  >,
  'getPendingSellerDetails' : ActorMethod<[], Array<SellerRegistration>>,
  'getPendingSellerRegistrations' : ActorMethod<[], Array<Principal>>,
  'getPlatformEarnings' : ActorMethod<[], bigint>,
  'getProductAverageRating' : ActorMethod<[string], number>,
  'getProductReviews' : ActorMethod<[string], Array<Review>>,
  'getProductVariants' : ActorMethod<[string], Array<ProductVariant>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getReferralCode' : ActorMethod<[], string>,
  'getReferralStats' : ActorMethod<[], ReferralStats>,
  'getReturnRequestByOrder' : ActorMethod<[string], [] | [ReturnRequest]>,
  'getReviewSummaries' : ActorMethod<[], Array<ReviewSummary>>,
  'getSavedAddresses' : ActorMethod<[], Array<SavedAddress>>,
  'getSellerOrders' : ActorMethod<[Principal], Array<Order>>,
  'getSellerProducts' : ActorMethod<[Principal], Array<Product>>,
  'getSellerProfileData' : ActorMethod<[Principal], [] | [SellerProfileData]>,
  'getSellerReviews' : ActorMethod<[Principal, bigint], Array<Review>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserOrders' : ActorMethod<[Principal], Array<Order>>,
  'getUserProducts' : ActorMethod<[Principal], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isCallerSellerApproved' : ActorMethod<[], boolean>,
  'isInWishlist' : ActorMethod<[string], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listCoupons' : ActorMethod<[], Array<CouponPublic>>,
  'placeOrder' : ActorMethod<[Order], undefined>,
  'redeemLoyaltyPoints' : ActorMethod<[bigint, bigint], RedeemResult>,
  'registerAsSeller' : ActorMethod<[string, [] | [string]], undefined>,
  'rejectReturn' : ActorMethod<
    [string, [] | [string]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'rejectSeller' : ActorMethod<[Principal], undefined>,
  'removeFromWishlist' : ActorMethod<[string], boolean>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitReturnRequest' : ActorMethod<
    [string, string],
    { 'ok' : ReturnRequest } |
      { 'err' : string }
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
  'updateProductVariants' : ActorMethod<
    [string, Array<ProductVariant>],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateSavedAddress' : ActorMethod<
    [SavedAddress],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateSellerOrderStatus' : ActorMethod<
    [
      string,
      { 'shipped' : null } |
        { 'cancelled' : null } |
        { 'pending' : null } |
        { 'paid' : null } |
        { 'approved' : null } |
        { 'return_requested' : null } |
        { 'return_approved' : null } |
        { 'delivered' : null } |
        { 'return_rejected' : null },
    ],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'validateCoupon' : ActorMethod<
    [string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];